### PR TITLE
Remove Buttons Test

### PR DESCRIPTION
**Pull request by kengdoj**
Closes Issue #247

### CODE REVIEW

**Comment by kengdoj** [comment]
Removed "controls" so it's "form components" as discussed in today's TT meeting. Also added more direct references to accname comp for form components.

@AnnMarieDavis Re-review requested please.

**Comment by cliffbert** [comment]
> I like all these changes to forms. My only additional suggestion is related to the streamline process for links at the bottom of this section.
> 
> The phrasing is awkward: In cases where the link takes one to a document...
> Can we substitute "one" with "the user" ?

True.

**Comment by kengdoj** [comment]
As you wish...

**Comment by kengdoj** [comment]
Thank you @AnnMarieDavis for your review!

**Pull request merged**
