### PR TITLE
Update 15Headings.md

### PR DESCRIPTION
**Pull request by cliffbert**
Should still test for heading markup

### CODE REVIEW

**Comment by drewnielson** [comment]
Agreed - good change

**Comment by cliffbert** [comment]
For 21 should we even list 1.2.3? It’s level A and allows for text-only as an alternative

**Comment by cliffbert** [comment]
For 21 should we even list 1.2.3? It’s level A and allows for text-only as an alternative

Also are we just listing the techniques we are accepting?

**Comment by drewnielson** [comment]
I already merged into the ReviseFormat branch, but I think we should remove reference to 1.2.3. Since we are requiring conformance at Level AA, developers/vendors don't have the option to provide only a text alternative. They have to provide the audio description as required in 1.2.5. From the Understanding 1.2.5 article:
> If they wish to conform at Level AA, under Success Criterion 1.2.5 authors must provide an audio description

**Comment by drewnielson** [comment]
We are not listing all of the techniques we are accepting, but in some cases we are listing a technique specifically to highlight a requirement. Omitting a requirement doesn't mean we wouldn't accept it. We should probably make a note to clarify that somewhere in the document intro.

**Comment by cliffbert** [comment]
OK, let’s review this tomorrow.

**Comment by cliffbert** [comment]
That’s my draft for now. Are you sending Al a summary?

**Comment by drewnielson** [comment]
I’m just going to send the update in the morning. Maybe a little later
tonight.

**Pull request merged**
