### PR TITLE
Revert "Revised Format"

### PR DESCRIPTION
**Pull request by cliffbert**
Reverts Section508Coordinators/ICTTestingBaseline#35

### CODE REVIEW

**Comment by cliffbert** [comment]
Oops, I merged those files into the Master. Did a Revert, hope that reverses it!

**Comment by drewnielson** [comment]
Let's not worry about reverting. I think we might as well just keep them merged. Any new changes, we can continue to make in the branch and then merge again.

**Comment by cliffbert** [comment]
I’ll look at… plugin links?

**Comment by drewnielson** [comment]
Yep, plug-in links could be next.

**Pull request closed without merging**
