### PR TITLE
Update 10Flashing.md

### PR DESCRIPTION
**Pull request by drewnielson**
Made changes to include consideration for relative luminance and saturated reds

### CODE REVIEW

**Comment by drewnielson** [comment]
Relative luminance is really the same test for color contrast. Saturated red is really just a sub-set of relative luminance. If we can pull RGB values, then it is just a matter of comparing the R value to the combination of R, G, B.

**Comment by cliffbert** [comment]
Yes, but sounds like it would involve multiple screenshotting  until we get the colors we need to compare. At least with the tools I have in mind. Doable, but do we want to require it.

**Comment by drewnielson** [comment]
Just to clarify, the color contrast analyzer provides the option to display RGB values, so we can perform the test and make the necessary calculations using the current tools. Obviously would be nice to automate some of the calculation in a tool though.

As to whether to require it, I think the point is that if it doesn't include either a saturated red or pass the 10% threshold in relative luminance change, then we shouldn't worry about it. Yes, it might be difficult to measure, but if we don't add the consideration, then we could be failing things that are technically failures under the regulation (via WCAG).

**Comment by drewnielson** [comment]
Merging to parent branch to expedite further review

**Pull request merged**
